language: java
sudo: false
jdk:
  - openjdk8
install:
  - git update-index --chmod=+x gradlew
script:
# To get rid of  the "Downloading/Downloaded" lines we use: --batch-mode  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
# Starting with Maven 3.6.1, to get rid of  the "Downloading/Downloaded" lines we use: --no-transfer-progress
  mvn clean install --batch-mode  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn --no-transfer-progress
